name: Jekyll CD - Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: helaili/jekyll-action@2.0.5
      env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}